import os
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from typing import Dict, Any, List

from .models import ResearchIdeaInput, ProfessionalizationResult, ResearchBlueprint
from .ai_engine import professionalize_research_idea

app = FastAPI(
    title="Research Topic Professionalization AI API",
    description="Transforms rough research ideas into methodologically defensible research blueprints.",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# In-memory history for workspace versions
workspace_history: Dict[str, List[ProfessionalizationResult]] = {}

@app.post("/api/professionalize", response_model=ProfessionalizationResult)
def professionalize(payload: ResearchIdeaInput):
    if not payload.raw_idea or len(payload.raw_idea.strip()) < 3:
        raise HTTPException(status_code=400, detail="Ide riset tidak boleh kosong atau terlalu singkat.")
    
    session_key = "default_user_session"
    current_history = workspace_history.get(session_key, [])
    new_version_num = len(current_history) + 1
    
    result = professionalize_research_idea(payload, version=new_version_num)
    
    current_history.append(result)
    workspace_history[session_key] = current_history
    return result

@app.get("/api/history", response_model=List[ProfessionalizationResult])
def get_history():
    return workspace_history.get("default_user_session", [])

@app.post("/api/export/markdown")
def export_markdown(blueprint: ResearchBlueprint):
    md_content = f"""# RESEARCH BLUEPRINT
**Generated by AI Research Topic Professionalization System**

---

### Proposed Title:
**{blueprint.proposed_title}**

- **Research Field:** {blueprint.research_field}
- **Research Maturity Level:** {blueprint.research_maturity_level}
- **Feasibility Evaluation:** {blueprint.feasibility_score}

---

### 1. Research Problem & Background
**Problem Statement:**
{blueprint.research_problem}

**Academic Background:**
{blueprint.research_background}

**Research Gap:**
{blueprint.research_gap}

---

### 2. Objectives, Questions & Hypotheses
**Research Objective:**
{blueprint.research_objective}

**Research Questions:**
{chr(10).join(f"- {q}" for q in blueprint.research_questions)}

**Hypotheses:**
{chr(10).join(f"- {h}" for h in (blueprint.hypotheses or []))}

---

### 3. Variable Operationalization
- **Independent Variable(s) (X):** {', '.join(blueprint.independent_variables)}
- **Dependent Variable(s) (Y):** {', '.join(blueprint.dependent_variables)}
- **Control Variable(s) (Z):** {', '.join(blueprint.control_variables)}
- **Confounding Variable(s) (W):** {', '.join(blueprint.confounding_variables)}

---

### 4. Methodology & Research Design
- **Research Design:** {blueprint.research_design}
- **Target Population:** {blueprint.population}
- **Sample & Determination:** {blueprint.sample}
- **Sampling Technique:** {blueprint.sampling_technique}
- **Data Collection Procedures:** {blueprint.data_collection}
- **Research Instruments:** {blueprint.research_instruments}
- **Data Analysis & Modeling:** {blueprint.data_analysis}

**Recommended Statistical Methods:**
{chr(10).join(f"- {s}" for s in blueprint.recommended_statistical_methods)}

---

### 5. Contributions, Ethics & Limitations
- **Expected Contribution:** {blueprint.expected_contribution}
- **Potential Limitations:** {blueprint.potential_limitations}
- **Ethical Considerations:** {blueprint.ethical_considerations}
"""
    return {"markdown": md_content}

# Mount static files for frontend
frontend_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "frontend"))
if os.path.exists(frontend_dir):
    app.mount("/static", StaticFiles(directory=frontend_dir), name="static")

@app.get("/")
def read_root():
    index_file = os.path.join(frontend_dir, "index.html")
    if os.path.exists(index_file):
        return FileResponse(index_file)
    return {"message": "Research Topic Professionalization API is active. Frontend files loading..."}
